# Generated by Django 5.1.2 on 2024-11-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('description', models.TextField()),
                ('is_post', models.BooleanField()),
                ('image', models.FileField(default='images/default (2).jpg', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('ACH', 'Personal Achievements'), ('REL', 'Family & Loved Ones'), ('TRA', 'Travel & Exploration'), ('SPE', 'Celebrations & Special Events')], default='SPE', max_length=64)),
            ],
        ),
    ]
