# Generated by Django 5.1.2 on 2024-11-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='num_interest',
            field=models.IntegerField(default=0),
        ),
    ]
